<?php

namespace App\Media\Video;

use App\Jobs\ProcessMediaVideo;
use App\Media\Contracts\VideoProcessor;
use App\Media\Enums\MediaType;
use App\Media\Enums\ProcessingState;
use App\Media\Exceptions\UnsupportedFormatException;
use App\Media\Repositories\MediaRepository;
use App\Media\Storage\StorageManager;
use App\Models\Media;
use FFMpeg\Format\Video\X264;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use ProtoneMedia\LaravelFFMpeg\Drivers\UnknownDurationException;
use ProtoneMedia\LaravelFFMpeg\Support\FFMpeg as FFMpegFacade;

class LocalFfmpegVideoProcessor implements VideoProcessor
{
    protected const SUPPORTED_MIME_TYPES = [
        'video/mp4',
        'application/mp4',
        'video/quicktime',
        'video/x-msvideo',
        'video/x-matroska',
        'video/webm',
    ];

    public function __construct(
        protected MediaRepository $repository,
        protected StorageManager $storage,
        protected array $config = [],
    ) {}

    public function upload(UploadedFile $file): Media
    {
        $mimeType = $file->getMimeType() ?: $file->getClientMimeType();

        if (! $this->supports($mimeType)) {
            throw new UnsupportedFormatException(
                mimeType: $mimeType,
                driver: 'ffmpeg',
            );
        }

        $diskName = $this->storageDisk();
        $disk = Storage::disk($diskName);

        /*
        |--------------------------------------------------------------------------
        | Store original
        |--------------------------------------------------------------------------
        */

        $extension = strtolower($file->getClientOriginalExtension() ?: 'mp4');

        $originalFilename = Str::uuid().'.'.$extension;

        $originalPath = $this->originalsPath().'/'.$originalFilename;

        $file->storeAs(
            $this->originalsPath(),
            $originalFilename,
            $diskName
        );

        /*
        |--------------------------------------------------------------------------
        | Quick poster (inline, so the UI shows a thumbnail immediately)
        |--------------------------------------------------------------------------
        | A single frame grab is cheap relative to a full transcode. The final
        | poster (from the processed file) is regenerated by the async job.
        */

        $posterFilename = pathinfo($originalFilename, PATHINFO_FILENAME).'.jpg';

        $posterPath = $this->thumbnailsPath().'/'.$posterFilename;

        try {
            FFMpegFacade::fromDisk($diskName)
                ->open($originalPath)
                ->getFrameFromSeconds(2)
                ->export()
                ->save($posterPath);
        } catch (\Throwable) {
            // Poster generation is best-effort; the async job will retry.
        }

        /*
        |----------------------------------------------------------------------
        | Create the media record in "processing" state and dispatch the
        | async transcoding job so the HTTP response returns immediately.
        */

        $media = $this->repository->createFromUpload(
            file: $file,
            path: $originalPath,
            disk: $diskName,
            type: MediaType::Video,
            checksum: md5_file($disk->path($originalPath)),
            thumbnailPath: $posterPath,
            spritePath: null,
            spriteVttPath: null,
            status: ProcessingState::Processing->value,
            processingStartedAt: now()->toDateTimeString(),
        );

        ProcessMediaVideo::dispatch($media->id, 'transcode')->onQueue('videos');

        return $media;
    }

    public function compress(Media $media, array $options = []): Media
    {
        $disk = Storage::disk($media->disk);
        $inputPath = $media->path;
        $outputFilename = Str::uuid()->toString().'.mp4';
        $outputPath = $this->processedPath().'/'.$outputFilename;

        $crf = $options['crf'] ?? 23;
        $preset = $options['preset'] ?? 'slow';

        FFMpegFacade::open($disk->path($inputPath))
            ->export()
            ->inFormat(new X264)
            ->addFilter('-preset', $preset)
            ->addFilter('-crf', (string) $crf)
            ->save(Storage::disk($this->storageDisk())->path($outputPath));

        $newMetadata = $this->getVideoMetadataFromDisk($outputPath, $this->storageDisk());
        $fileSize = Storage::disk($this->storageDisk())->size($outputPath);

        return $this->updateMediaRecord($media, $outputPath, $fileSize, $newMetadata);
    }

    public function resize(Media $media, int $width, int $height): Media
    {
        $disk = Storage::disk($media->disk);
        $inputPath = $media->path;
        $outputFilename = Str::uuid()->toString().'.mp4';
        $outputPath = $this->processedPath().'/'.$outputFilename;

        FFMpegFacade::open($disk->path($inputPath))
            ->export()
            ->inFormat(new X264)
            ->resize($width, $height)
            ->save(Storage::disk($this->storageDisk())->path($outputPath));

        $newMetadata = $this->getVideoMetadataFromDisk($outputPath, $this->storageDisk());
        $fileSize = Storage::disk($this->storageDisk())->size($outputPath);

        return $this->updateMediaRecord($media, $outputPath, $fileSize, $newMetadata);
    }

    public function thumbnail(Media $media, array $options = []): Media
    {
        $disk = Storage::disk($media->disk);
        $inputPath = $media->path;
        $outputFilename = Str::uuid()->toString().'.jpg';
        $outputPath = $this->processedPath().'/'.$outputFilename;

        $time = $options['time'] ?? '00:00:01';

        // Convert time string to seconds
        $timeSeconds = $this->parseTimeToSeconds($time);

        FFMpegFacade::open($disk->path($inputPath))
            ->getFrameFromSeconds($timeSeconds)
            ->export()
            ->save(Storage::disk($this->storageDisk())->path($outputPath));

        $this->repository->update($media, [
            'metadata' => array_merge($media->metadata ?? [], [
                'thumbnail_path' => $outputPath,
                'thumbnail_disk' => $this->storageDisk(),
            ]),
        ]);

        return $media;
    }

    public function optimize(Media $media): Media
    {
        return $this->compress($media, ['crf' => 28, 'preset' => 'fast']);
    }

    public function supports(string $mimeType): bool
    {
        return in_array($mimeType, self::SUPPORTED_MIME_TYPES, true);
    }

    public function processAsync(Media $media, string $action, array $options = []): Media
    {
        ProcessMediaVideo::dispatch($media->id, $action, $options)->onQueue('videos');

        return $media;
    }

    public function handleCallback(array $payload, ?string $signature = null): Media
    {
        throw new \BadMethodCallException('LocalFfmpegVideoProcessor does not use webhooks.');
    }

    protected function getVideoMetadataFromDisk(string $path, string $disk): array
    {
        $ffmpeg = FFMpegFacade::open(Storage::disk($disk)->path($path));

        $duration = 0;

        try {
            $sec = $ffmpeg->getDurationInSeconds();

            if ($sec !== null && is_numeric($sec) && (float) $sec > 0) {
                $duration = (int) round((float) $sec);
            }
        } catch (UnknownDurationException) {
            // Phone webm often lacks duration header — fall back to raw ffprobe
            try {
                $abs = Storage::disk($disk)->path($path);
                $result = Process::run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', $abs]);

                if ($result->successful()) {
                    $out = trim($result->output());

                    if (is_numeric($out) && (float) $out > 0) {
                        $duration = (int) round((float) $out);
                    }
                }
            } catch (\Throwable) {
                // keep 0
            }
        } catch (\Throwable) {
            // keep 0
        }

        return [
            'width' => $ffmpeg->getVideoStream()?->get('width'),
            'height' => $ffmpeg->getVideoStream()?->get('height'),
            'duration' => $duration,
        ];
    }

    protected function getVideoMetadata(string $path): array
    {
        return $this->getVideoMetadataFromDisk($path, $this->storageDisk());
    }

    protected function parseTimeToSeconds(string $timeString): int
    {
        $parts = explode(':', $timeString);
        $seconds = 0;
        $multiplier = 1;

        while (count($parts) > 0) {
            $seconds += array_pop($parts) * $multiplier;
            $multiplier *= 60;
        }

        return $seconds;
    }

    protected function updateMediaRecord(Media $media, string $newPath, int $newSize, array $metadata): Media
    {
        $updateData = [
            'path' => $newPath,
            'size' => $newSize,
        ];

        if (isset($metadata['width'])) {
            $updateData['width'] = $metadata['width'];
        }
        if (isset($metadata['height'])) {
            $updateData['height'] = $metadata['height'];
        }
        if (isset($metadata['duration'])) {
            $updateData['duration'] = $metadata['duration'];
        }

        $this->repository->update($media, $updateData);

        return $media;
    }

    protected function originalsPath(): string
    {
        return $this->config['paths']['originals'] ?? 'media/originals';
    }

    protected function processedPath(): string
    {
        return $this->config['paths']['processed'] ?? 'media/processed';
    }

    protected function storageDisk(): string
    {
        return $this->config['storage_disk'] ?? 'public';
    }

    protected function thumbnailsPath(): string
    {
        return 'media/thumbnails';
    }

    protected function spritesPath(): string
    {
        return 'media/sprites';
    }

    protected function tempPath(): string
    {
        return 'media/temp';
    }

    protected function transcodeVideo(
        string $disk,
        string $input,
        string $output
    ): void {

        FFMpegFacade::fromDisk($disk)
            ->open($input)
            ->export()
            ->inFormat(new X264)
            ->addFilter('-preset', 'slow')
            ->addFilter('-crf', '23')
            ->save($output);
    }

    protected function generatePoster(
        string $disk,
        string $video,
        string $output
    ): void {

        FFMpegFacade::fromDisk($disk)
            ->open($video)
            ->getFrameFromSeconds(2)
            ->export()
            ->save($output);
    }

    protected function generateSprite(
        string $disk,
        string $video,
        string $sprite,
        string $vtt,
        int $duration,
        int $interval = 5,
        int $thumbWidth = 160,
        int $thumbHeight = 90,
        int $columns = 5,
    ): void {

        $storage = Storage::disk($disk);

        $videoPath = $storage->path($video);
        $spritePath = $storage->path($sprite);

        if (! is_dir(dirname($spritePath))) {
            mkdir(dirname($spritePath), 0755, true);
        }

        $frames = max(1, (int) ceil($duration / $interval));

        $rows = (int) ceil($frames / $columns);

        Process::run([
            'ffmpeg',
            '-y',
            '-i',
            $videoPath,
            '-vf',
            sprintf(
                'fps=1/%d,scale=%d:%d,tile=%dx%d',
                $interval,
                $thumbWidth,
                $thumbHeight,
                $columns,
                $rows,
            ),
            '-frames:v',
            '1',
            $spritePath,
        ])->throw();

        $this->generateSpriteVtt(
            disk: $disk,
            output: $vtt,
            duration: $duration,
            interval: $interval,
            thumbWidth: $thumbWidth,
            thumbHeight: $thumbHeight,
            columns: $columns,
        );
    }

    protected function generateSpriteVtt(
        string $disk,
        string $output,
        int $duration,
        int $interval,
        int $thumbWidth,
        int $thumbHeight,
        int $columns,
    ): void {

        $storage = Storage::disk($disk);

        $filename = basename($output, '.vtt').'.jpg';

        $lines = [
            'WEBVTT',
            '',
        ];

        $frames = max(1, (int) ceil($duration / $interval));

        for ($i = 0; $i < $frames; $i++) {

            $start = $i * $interval;

            $end = min(
                ($i + 1) * $interval,
                $duration
            );

            $column = $i % $columns;

            $row = intdiv($i, $columns);

            $x = $column * $thumbWidth;

            $y = $row * $thumbHeight;

            $lines[] =
                $this->formatTimestamp($start)
                .' --> '.
                $this->formatTimestamp($end);

            $lines[] =
                basename($output, '.vtt')
                .'.jpg'
                .'#xywh='
                .$x.','
                .$y.','
                .$thumbWidth.','
                .$thumbHeight;

            $lines[] = '';
        }

        $storage->put(
            $output,
            implode(PHP_EOL, $lines)
        );
    }

    protected function formatTimestamp(float $seconds): string
    {
        $hours = floor($seconds / 3600);

        $minutes = floor(($seconds % 3600) / 60);

        $secs = floor($seconds % 60);

        $milliseconds = ($seconds - floor($seconds)) * 1000;

        return sprintf(
            '%02d:%02d:%02d.%03d',
            $hours,
            $minutes,
            $secs,
            $milliseconds,
        );
    }
}
