name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer:v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install JS Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Assets
        run: pnpm build

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            cd /var/www/ulo

            git fetch origin
            git reset --hard origin/main

            composer install \
              --no-dev \
              --prefer-dist \
              --optimize-autoloader \
              --no-interaction

            php artisan migrate --force

            php artisan optimize:clear
            php artisan optimize

            sudo systemctl restart laravel-queue
            sudo systemctl restart laravel-scheduler