name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/ulo

            git pull origin main

            composer install --no-dev --optimize-autoloader

            cp .env.example .env    # only the first deployment if .env doesn't exist

            php artisan key:generate # only the first deployment

            php artisan migrate --force

            php artisan optimize:clear

            npm ci
            npm run build